### ISSUE TITLE
Use registry local mirror to speed up development

### ISSUE THREAD

**Issue by mcanevet** [camptocamp/k8s-demo#86]
https://rancher.com/docs/k3s/latest/en/installation/private-registry/
Should be possible by creating a file `/etc/rancher/k3s/registries.yaml` with:
```yaml
mirrors:
  docker.io:
    endpoint:
      - "http://mycustomreg.com:5000"
```
